name: interval_time_picker
description: A variant of the default Flutter Time Picker in which you can pick intervals.
version: 0.2.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter